In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.15.0'

## Data Preprocessing

In [4]:
dataset=pd.read_csv("Churn_Modelling.csv")
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

## Handling missing data

In [8]:
# There are no missing data in the dataset.
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


## Encoding Categorical data

### Label Encoding the "Gender" column

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [10]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### One hot encoding the "Georgraphy" column

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [12]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

## Splitting the dataset into training and testing

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=0)

## Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

## Building the ANN

In [15]:
#Initializing the ANN
ann=tf.keras.models.Sequential()

In [17]:
# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [20]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

In [24]:
ann.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

In [26]:
ann.fit(X_train,y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 281us/step - loss: 0.3427 - accuracy: 0.8581
Epoch 2/100
250/250 [==============================] - 0s 253us/step - loss: 0.3422 - accuracy: 0.8590
Epoch 3/100
250/250 [==============================] - 0s 251us/step - loss: 0.3417 - accuracy: 0.8595
Epoch 4/100
250/250 [==============================] - 0s 245us/step - loss: 0.3415 - accuracy: 0.8574
Epoch 5/100
250/250 [==============================] - 0s 249us/step - loss: 0.3411 - accuracy: 0.8602
Epoch 6/100
250/250 [==============================] - 0s 249us/step - loss: 0.3407 - accuracy: 0.8597
Epoch 7/100
250/250 [==============================] - 0s 247us/step - loss: 0.3400 - accuracy: 0.8604
Epoch 8/100
250/250 [==============================] - 0s 246us/step - loss: 0.3400 - accuracy: 0.8627
Epoch 9/100
250/250 [==============================] - 0s 254us/step - loss: 0.3397 - accuracy: 0.8619
Epoch 10/100
250/250 [==============================] - 0s 255us/step - l

250/250 [==============================] - 0s 254us/step - loss: 0.3324 - accuracy: 0.8609
Epoch 80/100
250/250 [==============================] - 0s 250us/step - loss: 0.3317 - accuracy: 0.8616
Epoch 81/100
250/250 [==============================] - 0s 249us/step - loss: 0.3324 - accuracy: 0.8624
Epoch 82/100
250/250 [==============================] - 0s 250us/step - loss: 0.3319 - accuracy: 0.8609
Epoch 83/100
250/250 [==============================] - 0s 248us/step - loss: 0.3319 - accuracy: 0.8624
Epoch 84/100
250/250 [==============================] - 0s 267us/step - loss: 0.3322 - accuracy: 0.8612
Epoch 85/100
250/250 [==============================] - 0s 250us/step - loss: 0.3321 - accuracy: 0.8625
Epoch 86/100
250/250 [==============================] - 0s 248us/step - loss: 0.3324 - accuracy: 0.8611
Epoch 87/100
250/250 [==============================] - 0s 248us/step - loss: 0.3321 - accuracy: 0.8615
Epoch 88/100
250/250 [==============================] - 0s 247us/step - loss:

In [27]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))

1/1 [==============================] - 0s 81ms/step


array([[0.03592346]], dtype=float32)